#!/usr/bin/env python3
import hashlib
import pathlib
import sys


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: ckb-data-hash <binary>", file=sys.stderr)
        return 2

    data = pathlib.Path(sys.argv[1]).read_bytes()
    digest = hashlib.blake2b(data, digest_size=32, person=b"ckb-default-hash").hexdigest()
    print(digest)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
