use crate::config::{ReportFormat, UdtxConfig, ProfileConfig, TokenKind};
use crate::error::TokenCliError;
use crate::keys::KeyManager;
use crate::rpc::RpcClient;
use ckb_sdk::rpc::ckb_indexer::{ScriptType, SearchKey, SearchMode};
use ckb_types::prelude::*;

pub async fn report(
    format: ReportFormat,
    config: &UdtxConfig,
    profile: &ProfileConfig,
    key_manager: &mut KeyManager,
) -> Result<(), TokenCliError> {
    let owner_name = "owner";
    let owner_account = config.accounts.get(owner_name)
        .ok_or_else(|| TokenCliError::AuthMissing {
            role: format!("owner account '{}' not found in config", owner_name),
        })?;

    let account = key_manager.load_account(owner_name, owner_account, profile)?;

    let client = RpcClient::new(&profile.rpc_url)?;

    let balance = client.get_balance(&account.address).await.unwrap_or(0);

    let kind = &config.token.kind;
    let contract = profile.contracts.get(match kind {
        TokenKind::Sudt => "sudt",
        TokenKind::Xudt => "xudt",
    });

    let mut total_amount: u128 = 0;
    let mut cell_count = 0;

    if let Some(contract) = contract {
        let contract_code_hash = ckb_types::packed::Byte32::from_slice(
            &hex::decode(contract.code_hash.trim_start_matches("0x"))
                .map_err(|e| TokenCliError::TxBuild { message: format!("invalid code hash: {}", e) })?
        ).map_err(|e| TokenCliError::TxBuild { message: format!("invalid code hash bytes: {}", e) })?;

        let lock_script_hash: [u8; 32] = account.lock_script.calc_script_hash().unpack();

        let udt_type_script = ckb_types::packed::Script::new_builder()
            .code_hash(contract_code_hash)
            .hash_type(match contract.hash_type.as_str() {
                "type" => ckb_types::core::ScriptHashType::Type,
                "data" | "data1" => ckb_types::core::ScriptHashType::Data,
                _ => ckb_types::core::ScriptHashType::Data,
            })
            .args(ckb_types::packed::Bytes::from(lock_script_hash.to_vec()))
            .build();

        let search_key = SearchKey {
            script: udt_type_script.clone().into(),
            script_type: ScriptType::Type,
            script_search_mode: Some(SearchMode::Exact),
            filter: None,
            with_data: Some(true),
            group_by_transaction: None,
        };

        let mut cursor = None;
        loop {
            let page = client.get_cells(search_key.clone(), 500, cursor.clone()).await?;
            for cell in &page.objects {
                if let Some(ref data) = cell.output_data {
                    let bytes = data.as_bytes();
                    if bytes.len() >= 16 {
                        let mut amount_bytes = [0u8; 16];
                        amount_bytes.copy_from_slice(&bytes[..16]);
                        let amount = u128::from_le_bytes(amount_bytes);
                        total_amount += amount;
                        cell_count += 1;
                    }
                }
            }
            if page.objects.len() < 500 {
                break;
            }
            cursor = Some(page.last_cursor);
        }
    }

    match format {
        ReportFormat::Markdown => {
            println!("# UDTX Token Report");
            println!();
            println!("## Project");
            println!("- **Name**: {}", config.project.name);
            println!();
            println!("## Token");
            println!("- **Kind**: {:?}", kind);
            println!("- **Symbol**: {}", config.token.symbol);
            println!("- **Decimals**: {}", config.token.decimals);
            println!("- **Supply Mode**: {:?}", config.token.supply_policy.mode);
            println!();
            println!("## Owner");
            println!("- **Address**: {}", account.address);
            println!("- **CKB Balance**: {} shannons", balance);
            println!();
            println!("## On-Chain State");
            println!("- **Network**: {:?}", profile.network_type);
            println!("- **RPC**: {}", profile.rpc_url);
            println!("- **Token Cells**: {}", cell_count);
            println!("- **Total Token Balance**: {}", total_amount);
            println!();
            println!("---");
            println!("_Generated by udtx-cli_");
        }
        ReportFormat::Json => {
            let report = serde_json::json!({
                "project": {
                    "name": config.project.name,
                },
                "token": {
                    "kind": format!("{:?}", kind),
                    "symbol": config.token.symbol,
                    "decimals": config.token.decimals,
                    "supply_mode": format!("{:?}", config.token.supply_policy.mode),
                },
                "owner": {
                    "address": account.address,
                    "ckb_balance": balance,
                },
                "chain": {
                    "network": format!("{:?}", profile.network_type),
                    "rpc_url": profile.rpc_url,
                },
                "state": {
                    "token_cells": cell_count,
                    "total_balance": total_amount.to_string(),
                },
            });
            println!("{}", serde_json::to_string_pretty(&report).map_err(|e| TokenCliError::TxBuild {
                message: format!("JSON serialization failed: {}", e),
            })?);
        }
    }

    Ok(())
}
